### ISSUE TITLE
Bug: index.hpp leaks memory

### ISSUE THREAD

**Issue by Green-Sky** [unum-cloud/usearch#138]
### Describe the bug

the simple c++ db (index.hpp) leaks. I ran it with asan, and got the following output:
```
=================================================================
==884330==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x7f8e43669587 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cc:104
    #1 0x559417f9d685 in unum::usearch::index_gt<unum::usearch::cos_gt<float, float>, unsigned long, unsigned int, std::allocator<char>, std::allocator<char> >::search_to_find_in_base_(unsigned int, unum::usearch::span_gt<float const>, unsigned long, unum::usearch::index_gt<unum::usearch::cos_gt<float, float>, unsigned long, unsigned int, std::allocator<char>, std::allocator<char> >::context_t&) const (/home/green/workspace/clip.cpp/build/bin/image-search+0x46685)
    #2 0x559417fa1883 in unum::usearch::index_gt<unum::usearch::cos_gt<float, float>, unsigned long, unsigned int, std::allocator<char>, std::allocator<char> >::search(unum::usearch::span_gt<float const>, unsigned long, unum::usearch::search_config_t) const (/home/green/workspace/clip.cpp/build/bin/image-search+0x4a883)
    #3 0x559417fa4053 in main (/home/green/workspace/clip.cpp/build/bin/image-search+0x4d053)
    #4 0x7f8e4301d082 in __libc_start_main ../csu/libc-start.c:308

Direct leak of 960 byte(s) in 24 object(s) allocated from:
    #0 0x7f8e43669587 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cc:104
    #1 0x559417f99b1e in unum::usearch::index_gt<unum::usearch::cos_gt<float, float>, unsigned long, unsigned int, std::allocator<char>, std::allocator<char> >::view(char const*) (/home/green/workspace/clip.cpp/build/bin/image-search+0x42b1e)
    #2 0x559417fa3820 in main (/home/green/workspace/clip.cpp/build/bin/image-search+0x4c820)
    #3 0x7f8e4301d082 in __libc_start_main ../csu/libc-start.c:308

Direct leak of 512 byte(s) in 1 object(s) allocated from:
    #0 0x7f8e43669587 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cc:104
    #1 0x559417fa0099 in unum::usearch::index_gt<unum::usearch::cos_gt<float, float>, unsigned long, unsigned int, std::allocator<char>, std::allocator<char> >::search(unum::usearch::span_gt<float const>, unsigned long, unum::usearch::search_config_t) const (/home/green/workspace/clip.cpp/build/bin/image-search+0x49099)
    #2 0x559417fa4053 in main (/home/green/workspace/clip.cpp/build/bin/image-search+0x4d053)
    #3 0x7f8e4301d082 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 2496 byte(s) leaked in 26 allocation(s).
```

### Steps to reproduce

checkout this pr https://github.com/monatis/clip.cpp/pull/5 (or main if merged)

### Expected behavior

no leakage :)

### USearch version

v0.19.3

### Operating System

ubuntu 20.04

### Hardware architecture

x86

### Which interface are you using?

C++ implementation

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Green-Sky** [comment]
why do you default bugs with the invalid tag?

**Comment by ashvardanian** [comment]
@Green-Sky thank you for opening the issue! We pre-set the invalid tag, cause its often easier to disable the ones that you don't need, rather than search for the tags that apply. As for the issue, @DarvinHarutyunyan and @davvard can you please check this?

**Comment by ashvardanian** [comment]
@gurgenyegoryan Can you please enable ASAN in our CI unit tests?

**Comment by gurgenyegoryan** [comment]
@ashvardanian  Yes, no problem, I'll add it now.

**Comment by ashvardanian** [comment]
@Green-Sky please let us know if v0.20 fixes the leaks 🤗

**Comment by Green-Sky** [comment]
can confirm, memory leak is fixed :)

also, you never removed the invalid tag :P

**Comment by ashvardanian** [comment]
Perfect, @Green-Sky! 

Our work interests seemingly intersect, and we would happily explore more collaboration opportunities over time.
Some of the other projects that immediately pop into mind are: 

- [UForm - improving over CLIP](https://github.com/unum-cloud/uform),
- [UCall - to serve efficient AI models](https://github.com/unum-cloud/ucall), 
- [SimSIMD - for hardware-accelerated metrics](https://github.com/ashvardanian/simsimd),

But there is even more in corporate and personal repos of our team-mates 🤗
