### ISSUE TITLE
Bug: Java lib cannot be found on maven

### ISSUE THREAD

**Issue by gaoxiao** [unum-cloud/usearch#143]
### Describe the bug

cloud.unum.usearch:0.2.3  this failed to resolve.

### Steps to reproduce

cloud.unum.usearch:0.2.3  this failed to resolve.

### Expected behavior

cloud.unum.usearch:0.2.3  should succeed.

### USearch version

0.2.3

### Operating System

android

### Hardware architecture

x86

### Which interface are you using?

C++ implementation

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gaoxiao** [comment]
mvn install also failed:

Could not find artifact cloud.unum:usearch:jar:0.2.3 in central (https://repo.maven.apache.org/maven2

**Comment by ashvardanian** [comment]
Can you try a recent version like 0.20.0?

**Comment by gaoxiao** [comment]
Thanks @ashvardanian 
Do you have any plan to support android platform? I tried to load the jar directly into android, it doesn't seem to work right now.

**Comment by ashvardanian** [comment]
@gaoxiao So did the newer version work with Gradle/Maven?

As for Android, sure! We are demand-driven, so if the community wants it - we will port it. Which package manager do you generally use for app development? If possible, please share more details about the error. 

> If you happen to use Discord, it may be an easier place for real-time collaboration and feature requests.

**Comment by gaoxiao** [comment]
> @gaoxiao So did the newer version work with Gradle/Maven?
> 
> As for Android, sure! We are demand-driven, so if the community wants it - we will port it. Which package manager do you generally use for app development? If possible, please share more details about the error.
> 
> > If you happen to use Discord, it may be an easier place for real-time collaboration and feature requests.

@ashvardanian I directly imported usearch-0.20.0.jar file to my Java project in Maven pom.xml, but still got error:
Exception in thread "main" java.lang.UnsatisfiedLinkError: no usearch in java.library.path


As for Android, I was able to build from source, but found some errors, here are obvious two:
1. https://github.com/unum-cloud/usearch/blob/main/java/cloud/unum/usearch/cloud_unum_usearch_Index.cpp#L158
dump_to method will crash because distances is NULL

2. https://github.com/unum-cloud/usearch/blob/main/java/cloud/unum/usearch/cloud_unum_usearch_Index.cpp#L48
capacity is default to 0.


I do use Discord, please kindly share a server invitation?

**Comment by ashvardanian** [comment]
@gaoxiao, Discord is the first icon in README: https://discord.gg/A6wxt6dS9j
