### ISSUE TITLE
Bug: Molecular Search (Bitwise Tanimoto) probably doesn't work well. 

### ISSUE THREAD

**Issue by mireklzicar** [unum-cloud/usearch#150]
### Describe the bug

I have tried the tutorial with bitwise tanimoto (by the way it should be MetricKind.Tanimoto, MetricKind.BitwiseTanimoto throws import error)

```
from usearch.index import Index, MetricKind
from rdkit import Chem
from rdkit.Chem import AllChem

import numpy as np

molecules = [Chem.MolFromSmiles('CCOC'), Chem.MolFromSmiles('CCO')]
encoder = AllChem.GetRDKitFPGenerator()

fingerprints = np.vstack([encoder.GetFingerprint(x) for x in molecules])
fingerprints = np.packbits(fingerprints, axis=1)

index = Index(ndim=2048, metric=MetricKind.BitwiseTanimoto)
labels = np.arange(len(molecules))

index.add(labels, fingerprints)
matches: Matches = index.search(fingerprints, 10)
```

The problem is, I tried it in practice (adding this way cca 100K molecules from chembl), and while the search speed is good, ithe results are nonsensical. 

Example query:
<img width="155" alt="Screenshot 2023-07-18 at 22 01 20" src="https://github.com/unum-cloud/usearch/assets/109360098/f4eaf062-fe3d-48d8-9ed0-ea0506234b99">

Example output:
<img width="509" alt="Screenshot 2023-07-18 at 22 01 37" src="https://github.com/unum-cloud/usearch/assets/109360098/aebd4482-27db-4360-a371-0b82f61117d0">

i haven't had the time to dive into details what might be wrong
another observation 

### Steps to reproduce

Take any dataset of molecules, I used chembl_31, add the molecule into index as per tutorial and display the results.

### Expected behavior

Expected output (ground truth best tanimoto neighbors on the dataset):
<img width="501" alt="Screenshot 2023-07-18 at 22 04 18" src="https://github.com/unum-cloud/usearch/assets/109360098/af9f288b-11c8-4000-a360-f2fc97913516">

### USearch version

latest

### Operating System

Ubuntu

### Hardware architecture

x86

### Which interface are you using?

Python bindings

### Contact Details

miroslav.lzicar@themama.ai

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Thank you for being so interested, @mireklzicar! It highly depends on the dataset and the fingerprinting techniques you use. Sometimes, I get 53% recall (self-recall of present molecules), which is only slightly better than a coin flip. But there is a way to make it work with 100% accuracy. I will share a longer post on that topic in a few days. Hopefully, it's not too urgent.

**Comment by mireklzicar** [comment]
Thanks for quick response. If this works (let's say with classical morgan fingerprints and tanimoto similarity), we are very interested in our company. The hottest features for us are: high recall, scalability to millions or even billions and reasonable efficiency of index creation (i have noticed that in comparison to FAISS binary HNSW indexes, which were created in few seconds or minutes even on hundreds of million scale, with usearch it took hours/days or didnt even finish, including intense CPU usage).

**Comment by ashvardanian** [comment]
Interesting. Is there any more code to examine?

I am currently using it with 7 Billion molecules and it works fine.

> Feel free to reach out to me directly. Discord may be an easier place for real time communication.

**Comment by ashvardanian** [comment]
@mireklzicar, do you still face such issues? Please let me know if you do.

---

I've completed the construction of multiple Billion-scale molecule indexes. There should be no problems with speed, especially on Millions of entries. The datasets with 28 Billion embeddings/fingerprints, and the numerous pre-constructed indexes are already available. I'd happily hop on a call and help you start the project. A blog post is coming soon, but until then, here is a preview of what kind of performance you may expect.

<img width="1970" alt="USearch Molecules via MACCS*ECFP4" src="https://github.com/unum-cloud/usearch/assets/1983160/ed263a86-ec80-402f-b180-7a5e13bf7310">

On 10 Million molecules, USearch can perform around 200,000 search queries/s on a single CPU with 99% recall.

**Comment by mireklzicar** [comment]
@ashvardanian Cool! Looks very good. I am looking forward for the blog post. Some things I am especially interested in: a) how do the result molecules look? (pick some query molecules such as aspirin, benzene, olanzapine... and how the top10 or top20 molecules look, are they similar? do they have high fingerprint similarity to the query?). b) the figures end at 10M, but you are talking about 28Billion. Could you please report full figures (e.g. extend to 100M, 1B, 10B...)? c) how does it compare to faiss?

**Comment by ashvardanian** [comment]
@mireklzicar, hey! I’ve recently published a much larger report and the dataset, have you seen the [story](https://ashvardanian.com/posts/usearch-molecules/)?

- Repo: https://github.com/ashvardanian/usearch-molecules
- Story: https://ashvardanian.com/posts/usearch-molecules
- Bucket: https://registry.opendata.aws/usearch-molecules

Please let me know if you still face performance issues. Would also be happy to hear about your usecase. Are you on our [Discord](https://discord.gg/A6wxt6dS9j)?
