### ISSUE TITLE
Bug: JS keys should be `bigint`

### ISSUE THREAD

**Issue by gustavopch** [unum-cloud/usearch#178]
### Describe the bug

`Index::Add` currently validates the key expecting it to be a `number`.

### Steps to reproduce

N/A

### Expected behavior

The validation should expect it to be a `bigint`.

### USearch version

#20566e0ecdd99564150602dd96610e4be377e080

### Operating System

N/A

### Hardware architecture

Arm

### Which interface are you using?

Other bindings

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Hey, @gustavopch! I have put in your suggestions and preparing to merge them into the primary repo. Do you have any recommendations for the idiomatic way of writing tests for JS/TS packages? For now, it is trivial.

**Comment by gustavopch** [comment]
I think you can just use Node.js' new built-in test tools: https://nodejs.org/api/test.html

**Comment by gustavopch** [comment]
@ashvardanian I think you can just use Node.js' new built-in test tools: https://nodejs.org/api/test.html

**Comment by ashvardanian** [comment]
@gustavopch we also run those tests for WASM builds, and I am not sure this method will work in both places.
