### ISSUE TITLE
Bug: Seg Fault on index.add in Rust

### ISSUE THREAD

**Issue by tiagoml98** [unum-cloud/usearch#193]
### Describe the bug

I receive a segmentation fault when trying to add to an index in Rust, the error can be a direct segmentation fault or a "process didn't exit successfully", even when trying code from the docs. Is there something I am missing?

### Steps to reproduce

Create IndexOptions, create index, create a vector slice, and pass it into index.add() alongside a key

### Expected behavior

Index should add with no issues and be able to be searchable

### USearch version

1.1.1

### Operating System

Windows, Arch Linux

### Hardware architecture

x86

### Which interface are you using?

C++ implementation

### Contact Details

tiagoml98@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
[This](https://github.com/unum-cloud/usearch/tree/main/rust#quickstart) passes CI, so should probably work.

**Comment by tiagoml98** [comment]
I think that was it, thanks for the help!

**Comment by ashvardanian** [comment]
@tiagoml98, great! Let us know once you build something cool with it! [_Discord_](https://discord.gg/A6wxt6dS9j)
