### ISSUE TITLE
Bug: Python `Index.restore` returns `None` when called with `pathlib.Path` object

### ISSUE THREAD

**Issue by AleksandrKent** [unum-cloud/usearch#196]
### Describe the bug

`Index.restore` returns `None` when called with `pathlib.Path` object. I suppose this could be fixed by using `os.fspath` before passing `path` to `_index_dense_metadata`. If it works maybe it should be done everywhere in the module where `PathLike` object is passed to the `_compiled`. https://github.com/unum-cloud/usearch/blob/b7ec32c0bdd7ba496c6d7bbef209c889fb4bb1f6/python/usearch/index.py#L465-L471 

### Steps to reproduce

```python
from pathlib import Path
from usearch.index import Index
import numpy as np

# ensure there is no file prior to test
index_path = Path('index.usearch')
if index_path.exists():
    index_path.unlink()

index = Index(ndim=3)
vector = np.array([0.2, 0.6, 0.4])
index.add(42, vector)

index.save(index_path)
index.reset()

index = Index.restore(str(index_path))
assert index is not None  # okay

index = Index.restore(index_path)
assert index is not None  # assertion error
```

### Expected behavior

No AssertionError occurs.

### USearch version

v1.1.1

### Operating System

Ubuntu 22.04.2

### Hardware architecture

x86

### Which interface are you using?

Python bindings

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Thanks for noticing. Should have been solved by bc26b4e68560c65f992ea1b02979b40cdf65a3bd
