### ISSUE TITLE
Feature: support for retrieving metadata from index file in C interface

### ISSUE THREAD

**Issue by alexbarev** [unum-cloud/usearch#198]
### Describe what you are looking for

Hey, I found an unobvious behaviour with the Go code related to the index pointer and configuration. Here's what's going on:

1) In the Load function only the index pointer is set up, but the configuration is left with incorrect dimensions. https://github.com/unum-cloud/usearch/blob/e686a3dd66e2be5f7b376a56e779de90ce15c969/golang/lib.go#L341-L356

2) In the Get function, a vector is created with a length based on dimensions from config. https://github.com/unum-cloud/usearch/blob/e686a3dd66e2be5f7b376a56e779de90ce15c969/golang/lib.go#L289
    Same in the Search function https://github.com/unum-cloud/usearch/blob/e686a3dd66e2be5f7b376a56e779de90ce15c969/golang/lib.go#L306

3) The dimensions come from the config struct, but it looks like it might not be set up properly. Since the Load function doesn't set the dimensions, and user can forget to do that explicitly.

One solution might be to set dimensions in Load function. 

Or better to add support for metadata loading in C interface, as it is done for Python.

### Can you contribute to the implementation?

- [ ] I can contribute

### Is your feature request specific to a certain interface?

Other bindings

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Great catch! Should be an easy patch, will fix soon 🤗

**Comment by ashvardanian** [comment]
I believe this issue may have been resolved, isn't it @AleksandrKent ?
