### ISSUE TITLE
Feature: possibility of a streaming API?

### ISSUE THREAD

**Issue by philbooth** [unum-cloud/usearch#203]
### Describe what you are looking for

Caveat, this question may not make sense: I'm coming at it from a node.js perspective and have little understanding of the underlying C++ implementation.

When handling large datasets in node, it's customary to pass streams around instead of loading it all into memory as a string. Given that usearch can already serialize indices to disk, it would be really neat if I could open a stream when fetching/reading a document and connect it to a usearch index for streamed serialization.

Would something like even that be possible? I'd be happy to try and implement it if so, with guidance.

### Can you contribute to the implementation?

- [X] I can contribute

### Is your feature request specific to a certain interface?

C++ implementation

### Contact Details

pmbooth@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Hey, @philbooth! Thanks for reaching out!

I am not sure I understand correctly. We currently have a `view()` function, that allows viewing an index from disk, without loading it into RAM. Is that what you are looking for?

**Comment by philbooth** [comment]
Do you know what, I just realised this ticket makes no sense at all, sorry. Been looking at lots of different dependencies this morning and got myself mixed up. Ignore this, I'm closing it! 😊

**Comment by ashvardanian** [comment]
No worries, @philbooth! Don't hesitate to ping us if you have any cool ideas on your mind, and please share a link to what you build using USearch on our [Discord](https://discord.gg/A6wxt6dS9j) - contributors will be very excited 🤗
