### ISSUE TITLE
Documenting Memory Usage

### ISSUE THREAD

**Issue by ashvardanian** [unum-cloud/usearch#244]
### Describe what you are looking for

Recent benchmarks by @davvard suggest, that even for the same `f32` vectors USearch uses up to 4x less memory than FAISS. We should double-check those numbers and measure the memory consumption on the same test dataset we have used in the [FAISS comparison on the front page](https://github.com/unum-cloud/usearch#comparison-with-faiss).

### Can you contribute to the implementation?

- [X] I can contribute

### Is your feature request specific to a certain interface?

It applies to everything

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patelprateek** [comment]
@ashvardanian : 4x less memory consumption looks amazing . I would like to try this in some production use case. Can you give some pointers to why reduced memory usage ? 
Also how does this compare with nmslib/hnswlib. When you mention faiss which particular ann algorithm you compare against (i assume faiss's implementation of hnsw)

**Comment by ashvardanian** [comment]
@patelprateek, you are right, we are comparing against IndexHNSW. The memory consumption is much lower, cause we don’t use any STL containers and default memory allocators. Everything is handcrafted for HNSW :)

**Comment by ashvardanian** [comment]
@patelprateek, we’ve recently published a [large study](https://www.unum.cloud/blog/2023-11-07-scaling-vector-search-with-intel), describing the tradeoff between speed, recall and memory usage along other things. We align along the recall curves, and in that case memory consumption isn’t better, but speed can be orders of magnitude higher.

It’s probably worth comparing with other engines as well, but we are currently focused more on features, than broader benchmarks. Don’t hesitate to reach out and share your use-case with us on [Discord](https://discord.gg/A6wxt6dS9j) 🤗
