### ISSUE TITLE
Bug:  Add/search function use questions

### ISSUE THREAD

**Issue by NauhWuun** [unum-cloud/usearch#273]
### Describe the bug

I used the C++ example on the official website, but I encountered a problem with the add and search function. I don’t know which function should be used here in metric_at&& metric. The following is the official website code. 

I hope you can give me an example that can be used. Thank you.

### Steps to reproduce

index_gt<metric_cos_gt<float>> index;
float vec[3] = {0.1, 0.3, 0.2};

index.reserve(10);
index.add(/* key: */ 42, /* vector: */ {&vec[0], 3});  ??? has problem.
auto results = index.search(/* query: */ {&vec[0], 3}, 5 /* neighbors */);

### Expected behavior

I hope you can give me a case where C++ can be used

### USearch version

lastest

### Operating System

windows 11

### Hardware architecture

x86

### Which interface are you using?

C++ implementation

### Contact Details

nauhwuun2009@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Oh, the example may be describing the interface to the high-level API located in the index_dense.hpp. 

What’s your use case like? If you only plan to search through dense vectors - I’d recommend using the high-level variant.

**Comment by NauhWuun** [comment]
Can you give me a complete and usable example of reserve(), add(), search(), size(), capacity(), save(), load(), view()? Although I don't know what the high-level variant usage is, I just used it. I hope you can help me. Thank you.

**Comment by NauhWuun** [comment]
It would be best if you could give a more complete case. Due to the lack of documentation, the code looks very laborious, but I like to use C++ to achieve high-quality projects, so I hope it can help. Thanks again

**Comment by ashvardanian** [comment]
Sure, @NauhWuun, I will do my best to help 🤗 

I'll upload more examples in a couple of hours. In the meantime, you can find the [docs of the high-level API on our website here](https://unum-cloud.github.io/usearch/cpp/reference.html#usearch-index-dense-hpp).

**Comment by NauhWuun** [comment]
> Sure, @NauhWuun, I will do my best to help 🤗
> 
> I'll upload more examples in a couple of hours. In the meantime, you can find the [docs of the high-level API on our website here](https://unum-cloud.github.io/usearch/cpp/reference.html#usearch-index-dense-hpp).

I'm so looking forward to it. It feels great. Looking forward to the good news. :)

**Comment by ashvardanian** [comment]
@NauhWuun, please check the [refreshed QuickStart for C++](https://github.com/unum-cloud/usearch/tree/main/cpp#usearch-for-c). Does it help?

**Comment by NauhWuun** [comment]
> 🎉 This issue has been resolved in version 2.6.1 🎉
> 
> The release is available on [GitHub release](https://github.com/unum-cloud/usearch/releases/tag/v2.6.1)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

cool! thx
