### ISSUE TITLE
Bug: MultiIndex returns strange search results

### ISSUE THREAD

**Issue by kimihailv** [unum-cloud/usearch#274]
### Describe the bug

MultiIndex (even from one index) gives wrong nearest neighbours.

### Steps to reproduce

```python
import numpy as np
from usearch.index import Indexes, Index

np.random.seed(42)
data = np.random.random((10_000, 256))

index = Index(ndim=256)
index.add(np.arange(data.shape[0]), data)

gt = np.arange(1000)[:, np.newaxis]
print('Single index recall@1:', (index.search(data[:1000], 1).keys == gt).sum(axis=1).mean())

multi = Indexes(
    indexes=[index]
)

print('Multi index recall@1:', (multi.search(data[:1000], 1).keys == gt).sum(axis=1).mean())
```

Output:

```
Single index recall@1: 0.927
Multi index recall@1: 0.001
```

### Expected behavior

Similar performance

### USearch version

2.5.1

### Operating System

Ubuntu 23.04

### Hardware architecture

x86

### Which interface are you using?

Python bindings

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Thanks for submitting the issue. I’ll patch it next week.

**Comment by ashvardanian** [comment]
This was just a matter of putting the return statement one line lower 🤦 
Thanks!
