### ISSUE TITLE
Bug: Java bindings throws Out of memory error

### ISSUE THREAD

**Issue by superkelvint** [unum-cloud/usearch#308]
### Describe the bug

Out of memory error with Java bindings.

### Steps to reproduce

Follow the Java [README](https://unum-cloud.github.io/usearch/java/) code:
```
Index index = new Index.Config().metric("cos").dimensions(2).build();
float vec[] = {10, 20};
index.add(42, vec);
int[] keys = index.search(vec, 5);
```
throws this error:

> Exception in thread "main" java.lang.Error: Out of memory!
> at cloud.unum.usearch.Index.c_add(Native Method)
> at cloud.unum.usearch.Index.add(Index.java:107)
> at TestUsearch.main(TestUsearch.java:14)

### Expected behavior

No error occurs.

### USearch version

2.8.10

### Operating System

Ubuntu 22.04

### Hardware architecture

x86

### Which interface are you using?

Other bindings

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThangTo** [comment]
I've encountered a similar error too

**Comment by ashvardanian** [comment]
Thank you, @superkelvint and @ThangTo! Looking into it and will hopefully have a solution tomorrow 🤗

**Comment by ThangTo** [comment]
@ashvardanian Thank you for updating to the new version, everything is ok. 
But I want to ask more about how I want to get the "cosine distance" after searching, currently the default is only [keys] _int[] keys = index.search(vec, 5);_
It's difficult without a "distance" result.

**Comment by ashvardanian** [comment]
@ThangTo, sure, we can change the Java interface to be more similar to other bindings. Any chance you or @superkelvint could contribute? Thank you!

**Comment by ThangTo** [comment]
@ashvardanian That is currently beyond my ability, I am having difficulty coding C/C++(never coded C/C++ before), can you help me. Haizz 
Maybe we need to wait for someone to contribute
