### ISSUE TITLE
Bug: macos release builds do not contain the library

### ISSUE THREAD

**Issue by comunidadio** [unum-cloud/usearch#322]
### Describe the bug

The zip files usearch_macOS_arm64_2.8.14.zip and usearch_macOS_amd64_2.8.14.zip only contain usearch.h but no library (.so or .dyld).

### Steps to reproduce

Download usearch_macOS_arm64_2.8.14.zip or usearch_macOS_amd64_2.8.14.zip and unzip.

### Expected behavior

The release should contain the library (libusearch_c.so/dyld)

### USearch version

v2.8.14

### Operating System

macOS 14.2

### Hardware architecture

Arm

### Which interface are you using?

Other bindings

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ehsanul** [comment]
Note that this affects usage of the golang bindings with the latest releases. Using 2.7.4 is a fine workaround.

**Comment by ashvardanian** [comment]
I haven’t had a chance to look into it yet. @comunidadio and @ehsanul can you by any chance help fix this?

**Comment by sroussey** [comment]
The library being built is called `libusearch_c.dylib` but the script is assuming it is called `libusearch_c.so` so it is not being included in the ZIP file.

**Comment by ashvardanian** [comment]
Nice catch, @sroussey! Then it would only take a wildcard to fix.

**Comment by phronmophobic** [comment]
This also seems to affect the Java bindings for mac osx. Maven only shows 2.8.12, 2.8.6, and 2.8.4 so the workaround of using 2.7.4 doesn't seem to be an option (see https://mvnrepository.com/artifact/cloud.unum/usearch). 

Related: the docs for java show 2.8.11 which doesn't seem to be available on maven (https://unum-cloud.github.io/usearch/java/).

**USearch version**
v2.8.4 and v2.8.12

**Operating System**
macOS 14.0

**Hardware architecture**
Arm

**Which interface are you using?**
Java

**Comment by ashvardanian** [comment]
@phronmophobic is it possible to mark only the major version for Java dependencies?

@ehsanul and @comunidadio, would you be open to patching the CI to match the right binaries, possibly using a wildcard?

**Comment by ashvardanian** [comment]
That's very cool, @phronmophobic!

As for the issue, it's solved now, will merge and release soon 🤗
