### ISSUE TITLE
Bug: Quantization enum not public in Golang SDK

### ISSUE THREAD

**Issue by comunidadio** [unum-cloud/usearch#326]
### Describe the bug

Quantization enums (f32, f16, f64, i8, b1) aren't accessible to users of Go SDK since Go requires capitalized public exported fields/methods (ie. should be F32, F16, ...)

https://github.com/unum-cloud/usearch/blob/c2463ca3a043c26e99f50cfbf31232a8a646d060/golang/lib.go#L59C1-L60C1

### Steps to reproduce

Can't use SDK's Quantization enum in IndexConfig as they are not exported.

### Expected behavior

Quantization enum values available to Go SDK users.

### USearch version

latest

### Operating System

macos

### Hardware architecture

Arm

### Which interface are you using?

Other bindings

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
You are right, @comunidadio! Would you be able to open a PR?

**Comment by ashvardanian** [comment]
It was solved by @laitassou in the latest release. @comunidadio let us know if it works and feel free to share more suggestions and patches for the Go SDK 🤗
