### ISSUE TITLE
Bug: Every new bug is marked as invalid!

### ISSUE THREAD

**Issue by sroussey** [unum-cloud/usearch#334]
### Describe the bug

Bug: Every new bug is marked as invalid!

### Steps to reproduce

create a new bug report

### Expected behavior

not be invalid

### USearch version

main

### Operating System

MacOS

### Hardware architecture

Arm

### Which interface are you using?

Other bindings

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
It should be easy to update the list of labels isn't it, @sroussey? I thought highlighting the presence of both labels would help people select the right one, don't you think? That's easy to change in the [`bug_report.yml`](https://github.com/unum-cloud/usearch/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml).

**Comment by sroussey** [comment]
https://github.com/unum-cloud/usearch/pull/337
