### ISSUE TITLE
Feature: Add TSV

### ISSUE THREAD

**Issue by sdan** [unum-cloud/usearch#344]
### Describe what you are looking for

add tsv export to visualize embeddings

### Can you contribute to the implementation?

- [ ] I can contribute

### Is your feature request specific to a certain interface?

It applies to everything

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Hi @sdan! Somehow missed this 🤦‍♂️ 
You should be able to achieve this quite easily by obtaining the `index.vectors` computed property, which returns a NumPy array. For visualizations I’d like to add a WebGL renderer later. 
TSV aside, I’d recommend using simple binary files for dropping/loading embeddings - that would be a lot faster 🤗
