### ISSUE TITLE
Bug: C# Loading usearch file exception

### ISSUE THREAD

**Issue by ErwanL08** [unum-cloud/usearch#345]
### Describe the bug

Hi first thing this lib is awesome thank you for this work . 

I writting an application console that embedded a list of sentence with fasttext. the result give me a FLoat[] of 300D. 
At the end i m saving the result in a specific path.
![image](https://github.com/unum-cloud/usearch/assets/16559628/692c30f2-72f5-4544-b11d-8c77fe9751b8)
If i do a search on the index it s working fine.

In a other function i try to loaded the saved index model and launch a search on it : 
![image](https://github.com/unum-cloud/usearch/assets/16559628/bdf73467-65f1-47f8-8042-374dd3504a6f)
and i have this exception : 
![image](https://github.com/unum-cloud/usearch/assets/16559628/bd2fefec-bb56-4442-84a0-d2a51821f4f8)

Do i miss something ? 

### Steps to reproduce

![image](https://github.com/unum-cloud/usearch/assets/16559628/692c30f2-72f5-4544-b11d-8c77fe9751b8)
![image](https://github.com/unum-cloud/usearch/assets/16559628/bdf73467-65f1-47f8-8042-374dd3504a6f)

### Expected behavior

no exception

### USearch version

2.8.16

### Operating System

windows 11

### Hardware architecture

x86

### Which interface are you using?

Other bindings

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Interesting. @ErwanL08 and @gebirgslok can you suggest a Pull Request extending the tests with a minimal case that can be used to reproduced the bug? I can try patching it then.

**Comment by gebirgslok** [comment]
> Interesting. @ErwanL08 and @gebirgslok can you suggest a Pull Request extending the tests with a minimal case that can be used to reproduced the bug? I can try patching it then.

Sure, i'll give it a try.

BR
Jens

**Comment by Geekyvk5** [comment]
Same issue, works until the save, but while loading the saved while throws an exception in C#.

**Comment by ashvardanian** [comment]
@Geekyvk5 , @gebirgslok , and @ErwanL08, I've just pushed v2.9.1 which seems to fix the issue. Please let me know if you still encounter it 🤗

**Comment by ErwanL08** [comment]
hi @ashvardanian thank you the bug is fix 👍
