### ISSUE TITLE
Feature: Provide Javascript SDK as ESM package 

### ISSUE THREAD

**Issue by AndiLeni** [unum-cloud/usearch#352]
### Describe what you are looking for

It would be nice if the JavaScript SDK would be available as an ESM package too.

### Can you contribute to the implementation?

- [ ] I can contribute

### Is your feature request specific to a certain interface?

Other bindings

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
@sroussey seems to have covered those in #342. Is that what you have in mind, @AndiLeni?

**Comment by sroussey** [comment]
This should be fixed now.
