### ISSUE TITLE
Add CocoaPods support 

### ISSUE THREAD

**Issue by ua741** [unum-cloud/usearch#367]
### Describe what you are looking for

What would you like to be added?

Add CocoaPods support as an alternative to Swift Package Manager for Usearch.
Why is this needed?

Frameworks like Flutter and React Native rely on CocoaPods for their plugin system. This makes it nearly impossible to distribute Usearch as a plugin for these frameworks.

### Can you contribute to the implementation?

- [ ] I can contribute

### Is your feature request specific to a certain interface?

Other bindings

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
That doesn't seem very hard to implement, will look into it 😉

**Comment by ashvardanian** [comment]
@ua741 I was [trying to integrate CocoaPods](https://github.com/unum-cloud/usearch/tree/main-dev/objc#installation), but it turned out to be more complex than I expected. Would it be possible to integrate as a Git submodule? Maybe we can try documenting that workflow together 🤗
