### ISSUE TITLE
Bug: segmentation fault loading usearch.sqlite extension on macOS M2

### ISSUE THREAD

**Issue by simonw** [unum-cloud/usearch#371]
### Describe the bug

I got error `zsh: segmentation fault  python` trying to run `conn.load_extension(usearch.sqlite)` on macOS (M2).

### Steps to reproduce

I ran `python -m pip install usearch` and then this:
```pycon
>>> import usearch
>>> usearch.sqlite
'/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/usearch/compiled.cpython-310-darwin.so'
>>> 
>>> import sqlite3
>>> import usearch
>>> 
>>> conn = sqlite3.connect(":memory:")
>>> conn.enable_load_extension(True)
>>> conn.load_extension(usearch.sqlite)
```
I got the error:

    zsh: segmentation fault  python

### Expected behavior

No segmentation fault.

### USearch version

2.9.2

### Operating System

macOS Sonoma 14.1.1 (23B81) on 64GB Apple M2 Max

### Hardware architecture

Arm

### Which interface are you using?

Python bindings

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Interesting! Will look into it today, @simonw 🤗

**Comment by ashvardanian** [comment]
The installation seems to work now. I've tested Python and director approach on an Arm Mac and on x86 Linux.

<img width="833" alt="Screenshot 2024-04-01 at 16 30 09" src="https://github.com/unum-cloud/usearch/assets/1983160/29d467d3-5b23-46c5-bf97-9278a1306ddd">

PS: Relates to #376 #373. @simonw and @raydelvecchio, does it work for you with 2.10.2 now?
