### ISSUE TITLE
Bug: usearch: cannot execute binary file

### ISSUE THREAD

**Issue by B1991ing** [unum-cloud/usearch#372]
### Describe the bug

Dear usearch development team,

I ran "pip install numpy usearch", but it shows error that "**usearch: cannot execute binary file**".  I already use chomd to chagnt the execuation  authorization as shown in the screenshot, still not work.

<img width="488" alt="截屏2024-03-31 08 24 23" src="https://github.com/unum-cloud/usearch/assets/155892166/08262a12-9aa1-4af7-8e92-1a9a648069c0">

Do you have any idea that how to solve it?

Best,

Bing

### Steps to reproduce

Dear usearch development team,

I ran "pip install numpy usearch", but it shows error that "**usearch: cannot execute binary file**".  I already use chomd to chagnt the execuation  authorization as shown in the screenshot, still not work.

<img width="488" alt="截屏2024-03-31 08 24 23" src="https://github.com/unum-cloud/usearch/assets/155892166/08262a12-9aa1-4af7-8e92-1a9a648069c0">

Do you have any idea that how to solve it?

Best,

Bing

### Expected behavior

work on the Rstudio on mac

### USearch version

11

### Operating System

macOS sonoma

### Hardware architecture

x86

### Which interface are you using?

C++ implementation

### Contact Details

bingsong@nwafu.edu.cn

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Hi @B1991ing! Sorry for the delay, but I a not sure what the issue is. You mention using C++ interface, while using `pip` to install it. If you install the Python library, how do you plan to execute it? You should probably `import` it into some project and then instantiate and `Index` before you can use it.
