### ISSUE TITLE
Bug: Download failed: usearch_sqlite_macos_arm64_2.10.0.dylib could not be found

### ISSUE THREAD

**Issue by simonw** [unum-cloud/usearch#373]
### Describe the bug

Got this after trying to upgrade to latest version to try the code from this issue again:
- #371
```bash
python -m pip install usearch -U
```
That worked:
```
Collecting usearch
  Downloading usearch-2.10.0-cp310-cp310-macosx_11_0_arm64.whl (398 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 398.2/398.2 kB 2.6 MB/s eta 0:00:00
Requirement already satisfied: numpy in /opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages (from usearch) (1.26.2)
Requirement already satisfied: tqdm in /opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages (from usearch) (4.65.0)
Installing collected packages: usearch
  Attempting uninstall: usearch
    Found existing installation: usearch 2.9.2
    Uninstalling usearch-2.9.2:
      Successfully uninstalled usearch-2.9.2
Successfully installed usearch-2.10.0
```
But then:
```pycon
Python 3.10.10 (main, Mar 21 2023, 13:41:05) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import usearch
/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/usearch/__init__.py:100: UserWarning: Will download `usearch_sqlite` binary from GitHub.
  warnings.warn("Will download `usearch_sqlite` binary from GitHub.", UserWarning)
/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/usearch/__init__.py:107: UserWarning: Download failed: https://github.com/unum-cloud/usearch/releases/download/v2.10.0/usearch_sqlite_macos_arm64_2.10.0.dylib could not be found.
  warnings.warn(f"Download failed: {e.url} could not be found.", UserWarning)
```

### Steps to reproduce

Try to use `import usearch` against latest release on an M2 Mac.

### Expected behavior

The SQLite extension should be downloaded - this should not be a 404:

https://github.com/unum-cloud/usearch/releases/download/v2.10.0/usearch_sqlite_macos_arm64_2.10.0.dylib

### USearch version

2.10.0

### Operating System

macOS Sonoma 14.1.1 (23B81) on 64GB Apple M2 Max

### Hardware architecture

Arm

### Which interface are you using?

Python bindings

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by simonw** [comment]
The error is coming from here: https://github.com/unum-cloud/usearch/blob/708fedecf516687b19df3b5f9be4bf3b1c91b824/python/usearch/__init__.py#L103-L110

Here's where that download URL is constructed:

https://github.com/unum-cloud/usearch/blob/708fedecf516687b19df3b5f9be4bf3b1c91b824/python/usearch/__init__.py#L25-L51

**Comment by ashvardanian** [comment]
I am trying to avoid a breaking change in how the SQLite module is loaded, and it really overcomplicates things. Working on a hot-fix now 🤗

**Comment by ashvardanian** [comment]
@simonw there are a couple of issues here. 

1. SQLite will add `.dylib` suffix at the end of the name looking for a `.dylib.dylib` file.
2. Even after succesfull download, my M2 Mac complains about the build compatibility.

```sh
>>> conn.load_extension(usearch.sqlite.removesuffix('.dylib'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
sqlite3.OperationalError: dlopen(/var/folders/r0/mw8phgys4lg_60kgh8xm_x780000gn/T/usearch_sqlite_macos_arm64_2.10.0.dylib, 0x000A): tried: '/var/folders/r0/mw8phgys4lg_60kgh8xm_x780000gn/T/usearch_sqlite_macos_arm64_2.10.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/r0/mw8phgys4lg_60kgh8xm_x780000gn/T/usearch_
```

That doesn't happen with local builds, so it's somewhere in the CI. Still checking 😉

**Comment by ashvardanian** [comment]
I am gonna change the import method, which is technical a breaking change and should trigger a major release, but assuming the low adoption of the SQLite API, I hope it's fine 🤗

**Comment by simonw** [comment]
It's not quite working for me still:
```pycon
```pycon
>>> import usearch
/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/usearch/__init__.py:100: UserWarning: Will download `usearch_sqlite` binary from GitHub.
  warnings.warn("Will download `usearch_sqlite` binary from GitHub.", UserWarning)
>>> import sqlite3
>>> conn = sqlite3.connect(":memory:")
>>> conn.enable_load_extension(True)
>>> conn.load_extension(usearch.sqlite_path())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'usearch' has no attribute 'sqlite_path'
>>> usearch.sqlite
'/var/folders/x6/31xf1vxj0nn9mxqq8z0mmcfw0000gn/T/usearch_sqlite_macos_arm64_2.10.0.dylib'
>>> conn.load_extension(usearch.sqlite)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
sqlite3.OperationalError: dlopen(/var/folders/x6/31xf1vxj0nn9mxqq8z0mmcfw0000gn/T/usearch_sqlite_macos_arm64_2.10.0.dylib.dylib, 0x000A): tried: '/var/folders/x6/31xf1vxj0nn9mxqq8z0mmcfw0000gn/T/usearch_sqlite_macos_arm64_2.10.0.dylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/x6/31xf1vxj0nn9mxqq8z0mmcfw0000gn/T/usearch_sqlite_macos_arm64_2.10.0.dylib.dylib' (no such file), '/var
>>> conn.lead_extension(usearch.sqlite.replace('.dylib', ''))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'sqlite3.Connection' object has no attribute 'lead_extension'. Did you mean: 'load_extension'?
>>> conn.load_extension(usearch.sqlite.replace('.dylib', ''))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
sqlite3.OperationalError: dlopen(/var/folders/x6/31xf1vxj0nn9mxqq8z0mmcfw0000gn/T/usearch_sqlite_macos_arm64_2.10.0.dylib, 0x000A): tried: '/var/folders/x6/31xf1vxj0nn9mxqq8z0mmcfw0000gn/T/usearch_sqlite_macos_arm64_2.10.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/x6/31xf1vxj0nn9mxqq8z0mmcfw0000gn/T/usearch_
```
It says it got `x86_64` but needed `arm64`.

Also note I had to strip the `.dylib` from the end of the path - plus `usearch.sqlite_path()` has been renamed usearch.sqlite` - that's a bug in this README: https://github.com/unum-cloud/usearch/blob/3fd51841664471fad12ef5c37f0d87e783a7c7a1/sqlite/README.md#L28-L33

**Comment by simonw** [comment]
I tried downloading this: https://github.com/unum-cloud/usearch/releases/download/v2.10.1/usearch_sqlite_macos_arm64_2.10.1.dylib

Then opening it like this:

```pycon
>>> conn.load_extension("/tmp/usearch_sqlite_macos_arm64_2.10.1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
sqlite3.OperationalError: dlopen(/tmp/usearch_sqlite_macos_arm64_2.10.1.dylib, 0x000A): tried: '/tmp/usearch_sqlite_macos_arm64_2.10.1.dylib' (code signature in <DCF25A47-045B-3D73-BE3E-6EF40C87A897> '/private/tmp/usearch_sqlite_macos_arm64_2.10.1.dylib' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes
```
I fixed that error by opening up the macOS System Preferences and going to Security and allowing that binary. On a second attempt:
```pycon
>>> conn.load_extension("/tmp/usearch_sqlite_macos_arm64_2.10.1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
sqlite3.OperationalError: dlsym(0x81325550, sqlite3_usearchsqlitemacosarm_init): symbol not found
```

**Comment by ashvardanian** [comment]
Yes, the right architecture wasn't selected in CI for the 2.10.0 build, that you are using. But the [2.10.1 should be fixing that](https://github.com/unum-cloud/usearch/issues/373#issuecomment-2030560736). The CI can take a couple of hours to complete all the tests and I will try again afterwards.

---

@simonw, your log, however, is quite handy, as it highlights another issue - SQLite is searching for a weird symbol name when loading the library - `sqlite3_usearchsqlitemacosarm_init`. That will be an issue even with the new installation. If you `git clone` and then `pip install -e .` locally, the issue won't happen.

Give me a few hors to polish this. Sorry for inconvenience, debugging GitHub CI is an absolute nightmare 🧠 🔫

**Comment by ashvardanian** [comment]
@simonw, can you please check the 2.10.3? It should work fine.
