### ISSUE TITLE
Bug: module 'usearch' has no attribute 'sqlite_path'

### ISSUE THREAD

**Issue by raydelvecchio** [unum-cloud/usearch#376]
### Describe the bug

Here's my code, directly from the USearch SQLite docs (https://github.com/unum-cloud/usearch/tree/main/sqlite):

`import usearch

import sqlite3

conn = sqlite3.connect("test.db")

conn.enable_load_extension(True)

conn.load_extension(usearch.sqlite_path())`

Running this code, when line 5 is reached, I receive an error stating *AttributeError: module 'usearch' has no attribute 'sqlite_path'*. 

I'm currently on usearch python version 2.8.15 (via `pip3 list`). 

### Steps to reproduce

1. Install usearch via `pip3 install usearch` (latest version, and the one I'm on, is 2.8.15) in a virtual environment.
2. Run the above code, and see the error.

### Expected behavior

The script should run without error and I should be able to operate with vectors within SQLite, as shown here: https://github.com/unum-cloud/usearch/tree/main/sqlite. Perhaps the documentation is outdated or incorrect?

### USearch version

2.8.15 

### Operating System

MacOS

### Hardware architecture

Arm

### Which interface are you using?

Python bindings

### Contact Details

ray@cerebralvalley.ai

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Hi @raydelvecchio! The docs are for the recent version 2.10+. Can you please refresh your installation?

**Comment by simonw** [comment]
I think `usearch.sqlite_path()` may have been renamed to `usearch.sqlite` - try that.

**Comment by ashvardanian** [comment]
@raydelvecchio, can you please check the 2.10.3? It should work fine.
