### ISSUE TITLE
Bug: crash when hardware concurrency is exceeded

### ISSUE THREAD

**Issue by mbautin** [unum-cloud/usearch#389]
### Describe the bug

When attempting to add vectors to the index using a number of threads that execeeds the hardware concurrency as reported by std::thread::hardware_concurrency(), a crash happens. Stack trace from a test (with AddressSanitizer) is available at https://gist.githubusercontent.com/mbautin/80c0d87a0915e7da7b076a055a382b9e/raw

The root cause seems to be an underflow of the available_threads_ vector. It is initialized as follows:
```
        available_threads_.resize(std::thread::hardware_concurrency());
        std::iota(available_threads_.begin(), available_threads_.end(), 0ul);
```

The crash happens in this function:
```
    thread_lock_t thread_lock_(std::size_t thread_id) const {
        if (thread_id != any_thread())
            return {*this, thread_id, false};

        available_threads_mutex_.lock();
        thread_id = available_threads_.back();
        available_threads_.pop_back();
        available_threads_mutex_.unlock();
        return {*this, thread_id, true};
    }
```

It is invoked from the add_ function as follows:
```
    template <typename scalar_at>
    add_result_t add_(                             //
        vector_key_t key, scalar_at const* vector, //
        std::size_t thread, bool force_vector_copy, cast_t const& cast) {

        if (!multi() && contains(key))
            return add_result_t{}.failed("Duplicate keys not allowed in high-level wrappers");

        // Cast the vector, if needed for compatibility with `metric_`
        thread_lock_t lock = thread_lock_(thread);
```

The `add` function is invoked with `thread = any_thread()`.

I see that this whole mechanism is ultimately needed for providing a "context" object corresponding to the thread. The user could enumerate all the threads that will be performing any index insertion or search operations, and pass a 0-based index of that thread as the `thread` parameter. It could be possible to call the reserve() function to set the correct threads_add and threads_search, but it does not seem intuitive.

```
inline index_limits_t(std::size_t n, std::size_t t) noexcept : members(n), threads_add(t), threads_search(t) {}
```

### Steps to reproduce

Run a test that performs more simultaneous concurrent indexing operations than the hardware concurrency.
Example test: https://gist.githubusercontent.com/mbautin/6ef7cbbc18b818c1ab969be55a74e899/raw (implemented in YugabyteDB's test framework -- should be easy to extract as an independent test).

### Expected behavior

The system should not crash. It should allow any number of indexing threads to run.

### USearch version

2.10.5

### Operating System

AlmaLinux 8.8

### Hardware architecture

x86

### Which interface are you using?

C++ implementation

### Contact Details

mbautin@users.noreply.github.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Just to clarify, does it work fine, if you use `index_limits_t` to increase the number of threads?

**Comment by ashvardanian** [comment]
Nice catch! I'll ship a patch in a couple of hours 🤗
