### ISSUE TITLE
Bug: Syntax Error with Jest in ESM

### ISSUE THREAD

**Issue by eryue0220** [unum-cloud/usearch#418]
### Describe the bug

When run test through Jest in ESM, it will occur an error like:
![image](https://github.com/unum-cloud/usearch/assets/3050418/02e9bf2a-5426-45e0-a196-09c564e76df0)

### Steps to reproduce

1. git clone https://github.com/eryue0220/usearch-jest-esm-bug
2. cd usearch-jest-esm-bug
3. pnpm i
4. pnpm test

### Expected behavior

It should pass without babel transform the code.

### USearch version

2.11.1

### Operating System

Mac OSX

### Hardware architecture

Arm

### Which interface are you using?

Other bindings

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eryue0220** [comment]
Currently, A workaround is provide a transform in jest to remove `module.exports` in source code: https://github.com/eryue0220/usearch-jest-esm-bug/blob/main/jest.config.mjs#L5

**Comment by ashvardanian** [comment]
I am very inexperienced in JS tooling. Any chance you could open a PR if you know how to fix that?

**Comment by eryue0220** [comment]
> I am very inexperienced in JS tooling. Any chance you could open a PR if you know how to fix that, @eryue0220?

Sure, I will fix this later.
