### ISSUE TITLE
Feature: adding `py.typed` metadata to `python/usearch`

### ISSUE THREAD

**Issue by jamesbraza** [unum-cloud/usearch#424]
### Describe what you are looking for

Running `mypy==1.9.0` with `usearch==2.12.0`:

```none
foo.py:5:1: error: Skipping analyzing "usearch.index": module is installed, but missing library stubs or py.typed marker  [import-untyped]
    from usearch.index import Index
    ^
```

It would be nice to add `py.typed` metadata for `mypy`

### Can you contribute to the implementation?

- [X] I can contribute

### Is your feature request specific to a certain interface?

Python bindings

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Cool, @jamesbraza! I don't have experience with that. So if it's not too much code to maintain and you can contribute, would love to merge it 🤗
