### ISSUE TITLE
Feature: WASM Build

### ISSUE THREAD

**Issue by andrewluetgers** [unum-cloud/usearch#45]
### Describe what you are looking for

I would like to run this off-line in the browser have you considered adding a WASM build?

### Can you contribute to the implementation?

- [ ] I can contribute

### Is your feature request specific to a certain interface?

Other

### Contact Details

andrew.luetgers@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Sure, we have been discussing it with @syrusakbary. Haven’t built it yet, but happy to try if you have an application 🤗

**Comment by andrewluetgers** [comment]
Yeah - I'm working on a chrome extension for personal knowledge management / research. It uses SQLite for offline data. There is a big gap in the space that SQLite occupies for a solid vector search database. Perhaps I should have asked about the possibility of a SQLite extension instead. Either one would be fantastic and I think widely useful.

**Comment by aehlke** [comment]
I'm also highly interested in this, in order to build it into an iOS app via WKWebView running user scripts.

**Comment by ashvardanian** [comment]
@aehlke You can use it in both Swift and Objective C even without WebKit.

**Comment by aehlke** [comment]
I'll do that but would also like to let users have it run in the frontend of statically-deployed sites the users can deploy from my app. Thanks

**Comment by ashvardanian** [comment]
Hey, @aehlke ! Not only the WASM builds are available for a couple of releases now, but we have also based Emscripten-based WASM bindings on top of our C99 interface. They are already available on [wasmer.io/unum/usearch](https://wasmer.io/unum/usearch), and we are already working on next-gen WAI interfaces!

Let us know about your experience and please share if you have a cool application in mind 🤗
