### ISSUE TITLE
Bug: pip install can't find correct version ， usearch can't support  ubuntu x86_64?

### ISSUE THREAD

**Issue by yank666** [unum-cloud/usearch#464]
### Describe the bug

pip install can't find correct version 

### Steps to reproduce

pip install usearch

### Expected behavior

![image](https://github.com/user-attachments/assets/84f73a31-eeb2-4b78-8378-3adc09a8e1f7)
pip install can't find correct version  in linux unbuntu

### USearch version

2.13.5

### Operating System

Ubuntu 18.04.6

### Hardware architecture

x86

### Which interface are you using?

Python bindings

### Contact Details

yank666@163.com

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
It looks like you are searching in some non-default indexes. Can you double-check that?

**Comment by pribadihcr** [comment]
Have similar problem. any solutions?

**Comment by ashvardanian** [comment]
Can you share more details about your environment?
