### ISSUE TITLE
Bug: Rust build failed on Windows PC

### ISSUE THREAD

**Issue by CCnut** [unum-cloud/usearch#477]
### Describe the bug

My PC with i5-10500 CPU, does not compile properly with rust bindings (using default features).

[This pull](https://github.com/unum-cloud/usearch/pull/472) may solve some problems.

[build.log](https://github.com/user-attachments/files/16781406/build.log)

### Steps to reproduce

Add package and build

### Expected behavior

Build success

### USearch version

2.15.0

### Operating System

Windows 10

### Hardware architecture

x86

### Which interface are you using?

Other bindings

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Thanks for noting, @CCnut! I'm merging the mentioned PR. Please let me know if it doesn't solve your issue ;)

**Comment by ashvardanian** [comment]
It would help if anyone could add a Rust test into the `prerelease.yaml` CI for Windows 🤗 

cc @brkp, @CCnut

**Comment by ashvardanian** [comment]
Thank you @brkp! Much appreciated ;)
