### ISSUE TITLE
Question: query performance without loading full index into mem?

### ISSUE THREAD

**Issue by ucasfl** [unum-cloud/usearch#483]
### Describe what you are looking for

> The latter allows you to serve indexes from external memory, enabling you to optimize your server choices for indexing speed and serving costs. This can result in 20x cost reduction on AWS and other public clouds.

```
other_view = Index(ndim=..., metric=...)
other_view.view("index.usearch")
```
Hi, usearch is great vector search library, and I saw that we can view the index without loading it into RAM fully, do we have any performance benchmark in this case, and how about comparing with the case loading full index into RAM?

### Can you contribute to the implementation?

- [ ] I can contribute

### Is your feature request specific to a certain interface?

It applies to everything

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
This highly depends on the latency if your SSDs.
