### ISSUE TITLE
Bug: StringZilla not correctly installed

### ISSUE THREAD

**Issue by Spixmaster** [unum-cloud/usearch#522]
### Describe the bug

In file "sqlite/lib.cpp" call `#include "../stringzilla/c/lib.c"` happens. However when installing StringZilla with CMake that file is not installed.

### Steps to reproduce

"c/lib.c" should be installed with StringZilla.

### Expected behavior

File exists.

### USearch version

v2.16.0

### Operating System

Arch Linux

### Hardware architecture

x86

### Which interface are you using?

C++ implementation

### Are you open to being tagged as a contributor?

- [ ] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
You shouldn’t use local installations for those builds, only the git submodules.
