### ISSUE TITLE
Bug: Do not use submodule but system-wide dependencies

### ISSUE THREAD

**Issue by Spixmaster** [unum-cloud/usearch#523]
### Describe the bug

System-wide dependencies should be used and then link the library file.

```sh
❯ cmake -D USEARCH_BUILD_TEST_C=ON -D USEARCH_BUILD_TEST_CPP=ON -D USEARCH_BUILD_LIB_C=ON -D USEARCH_USE_FP16LIB=ON -D USEARCH_USE_SIMSIMD=ON ..
CMake Deprecation Warning at CMakeLists.txt:3 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Configuring done (0.3s)
CMake Error at c/CMakeLists.txt:9 (add_executable):
  Cannot find source file:

    ../simsimd/c/lib.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc


CMake Error at c/CMakeLists.txt:9 (add_executable):
  No SOURCES given to target: test_c


CMake Error at c/CMakeLists.txt:19 (add_library):
  No SOURCES given to target: usearch_c


CMake Error at c/CMakeLists.txt:20 (add_library):
  No SOURCES given to target: usearch_static_c


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

### Steps to reproduce

Run the command.

### Expected behavior

No error.

### USearch version

v2.16.0

### Operating System

Arch Linux

### Hardware architecture

x86

### Which interface are you using?

C++ implementation

### Are you open to being tagged as a contributor?

- [ ] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Spixmaster** [comment]
You can even use submodules but then do `#include <a.hpp>` and not  `#include <../a.hpp>`. This is possible by adding `target_include_directories(${PROJECT_NAME} PUBLIC "./path/")` to "CMakeLists.txt".

**Comment by Spixmaster** [comment]
I packaged the software and that makes it troublesome, https://aur.archlinux.org/packages/usearch.

**Comment by ashvardanian** [comment]
This was an important design decision, and I’ve chosen submoduled instead. They make both the development and packaging much easier across most platforms.
