### ISSUE TITLE
Bug: Msan use-of-uninitialized-value in `simsimd_kl_f16_sapphire`

### ISSUE THREAD

**Issue by rschu1ze** [unum-cloud/usearch#525]
### Describe the bug

In https://github.com/ClickHouse/ClickHouse/pull/69387, I am trying to enable the SimSIMD backend of Usearch. This PR has been open for a while as I was waiting for Usearch 2.16 (related [issue](https://github.com/ashvardanian/SimSIMD/issues/175)).

The CI of ClickHouse runs all tests on ubsan, msan and tsan builds. In the PR, one of the tests fails in msan builds with this error:

```
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
==610==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x556ea9d7e84f in simsimd_kl_f16_sapphire build_docker/./contrib/SimSIMD/include/simsimd/probability.h:553:15
    #1 0x556ea9d6ed40 in simsimd_kl_f16 build_docker/./contrib/SimSIMD/c/lib.c:179:1
    #2 0x556ea9d6ed40 in simsimd_capabilities build_docker/./contrib/SimSIMD/c/lib.c:289:5
    #3 0x556e9bef7bf5 in unum::usearch::metric_punned_t::configure_with_simsimd() build_docker/./contrib/usearch/include/usearch/index_plugins.hpp:1875:59
    #4 0x556e9bef7bf5 in unum::usearch::metric_punned_t::builtin(unsigned long, unum::usearch::metric_kind_t, unum::usearch::scalar_kind_t) build_docker/./contrib/usearch/include/usearch/index_plugins.hpp:1728:21
    #5 0x556e9bef7bf5 in unum::usearch::metric_punned_t::metric_punned_t(unsigned long, unum::usearch::metric_kind_t, unum::usearch::scalar_kind_t) build_docker/./contrib/usearch/include/usearch/index_plugins.hpp:1701:27
    #6 0x556e9bef7bf5 in DB::USearchIndexWithSerialization::USearchIndexWithSerialization(unsigned long, unum::usearch::metric_kind_t, unum::usearch::scalar_kind_t, DB::UsearchHnswParams) build_docker/./src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp:112:28
```

([full stracktrace](https://s3.amazonaws.com/clickhouse-test-reports/69387/3a042c080473957ffe40c5e299b06714868ab841/stateless_tests__msan__[2_4]/stderr.log))

The issue did not reproduce for me locally, likely because my system did not execute the Sapphire code path (SimSIMD is compiled with runtime dispatch and I use an Ice-Lake-era CPU that is too old).

This happens during the initialization of the function pointers to the SIMD routines:

```cpp
[...]

simsimd_distance_t dummy_results_buffer[2];
simsimd_distance_t *dummy_results = &dummy_results_buffer[0];
void *x = 0;

[...]

simsimd_kl_f16((simsimd_f16_t *)x, (simsimd_f16_t *)x, 0, dummy_results);
```

SIMD implementation with line numbers:

```
528 SIMSIMD_PUBLIC void simsimd_kl_f16_sapphire(simsimd_f16_t const *a, simsimd_f16_t const *b, simsimd_size_t n,
529                                             simsimd_distance_t *result) {
530     __m512h sum_vec = _mm512_setzero_ph();
531     __m512h epsilon_vec = _mm512_set1_ph((simsimd_f16_t)SIMSIMD_F16_DIVISION_EPSILON);
532     __m512h a_vec, b_vec;
533
534 simsimd_kl_f16_sapphire_cycle:
535     if (n < 32) {
536         __mmask32 mask = (__mmask32)_bzhi_u32(0xFFFFFFFF, n);
537         a_vec = _mm512_maskz_add_ph(mask, _mm512_castsi512_ph(_mm512_maskz_loadu_epi16(mask, a)), epsilon_vec);
538         b_vec = _mm512_maskz_add_ph(mask, _mm512_castsi512_ph(_mm512_maskz_loadu_epi16(mask, b)), epsilon_vec);
539         n = 0;
540     }
541     else {
542         a_vec = _mm512_add_ph(_mm512_castsi512_ph(_mm512_loadu_epi16(a)), epsilon_vec);
543         b_vec = _mm512_add_ph(_mm512_castsi512_ph(_mm512_loadu_epi16(b)), epsilon_vec);
544         a += 32, b += 32, n -= 32;
545     }
546     __m512h ratio_vec = _mm512_div_ph(a_vec, b_vec);
547     __m512h log_ratio_vec = _simsimd_log2_f16_sapphire(ratio_vec);
548     __m512h prod_vec = _mm512_mul_ph(a_vec, log_ratio_vec);
549     sum_vec = _mm512_add_ph(sum_vec, prod_vec);
550     if (n) goto simsimd_kl_f16_sapphire_cycle;
551
552     simsimd_f32_t log2_normalizer = 0.693147181f;
553     *result = _mm512_reduce_add_ph(sum_vec) * log2_normalizer;
554 }
```

All of this looks good to me (i.e. no uninitialized value) but perhaps you like to double-check if I missed something. MemorySanitizer is usually right 😄

(If this is indeed a false positive, I'll disable msan instrumentation in ClickHouse's SimSIMD fork.)

### Steps to reproduce

(no need to reproduce the issue)

### Expected behavior

No msan finding

### USearch version

latest and greatest

### Operating System

Latest Ubuntu

### Hardware architecture

x86

### Which interface are you using?

C++ implementation

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
@rschu1ze, in my experience, sanitizers can't handle masked loads in AVX-512. May be worth opening an issue in the sanitizer repo 🤷

**Comment by rschu1ze** [comment]
@ashvardanian Thanks, since this is a false positive, I suppressed the issue: https://github.com/ClickHouse/SimSIMD/commit/c03d065a7661004a9a18fe52753efafa170c67f9 . Let's close this issue.
