### ISSUE TITLE
Bug: adding int8 vector does not add arr[0], but adds arr[:, 0], how to solve it?

### ISSUE THREAD

**Issue by arditobryan** [unum-cloud/usearch#543]
### Describe the bug

The bug is strange, it does not cause the same error with a regular numpy array (hence I cannot simply reproduce it with a random numpy vector), but this is what I am getting:

### Steps to reproduce

```
>>> import numpy as np
>>> from usearch.index import Index
>>> import random

>>> index = Index(
    ndim=384, # Define the number of dimensions in input vectors
    metric='cos', # Choose 'l2sq', 'haversine' or other metric, default = 'ip'
    dtype='i8', # Quantize to 'f16' or 'i8' if needed, default = 'f32'
    connectivity=16, # Optional: How frequent should the connections in the graph be
    expansion_add=128, # Optional: Control the recall of indexing
    expansion_search=64, # Optional: Control the quality of search
)

# this is the array i want to add to the index
>>> quantized_tfQ = quantized_tfQ.astype(np.int8)
>>> quantized_tfQ
array([[  95,  -67,   77, ...,    1,   -4,  -34],
       [  48,  -37,  -41, ...,   54,   97,  -22],
       [-128,   93,  -20, ...,    3,   68,   18],
       ...,
       [  15,  -27,   40, ...,  -14,  -66,   33],
       [ -17,  -71,   49, ...,  -47,  -44,  -26],
       [  55,  -29,   52, ...,    6,   18,  -69]], dtype=int8)

# indexing the array
>>> index.add(list(range(len(quantized_tfQ))), quantized_tfQ)

>>> index.get(0)[0:5]
array([  95,   48, -128,   65,   60], dtype=int8)

If I compare it with the first 5 elements in the first sample:
>>> quantized_tfQ[0][0:5]
array([ 95, -67,  77, -52, 101], dtype=int8)
```

The data I am getting from the index are the exact elements of quantized_tfQ[:, 0] (up to 384), why is this happening? Have I been processing the numpy in a different way?

When trying to get index n. 1:
```
>>> index.get(1)[0:5]
array([  48, -128,   65,   60,  -66], dtype=int8)
```
The behavior is even more strange, it shifts the data of one vertical position

### Expected behavior

The indexing should add each sample with its corresponding index

### USearch version

2.16.8

### Operating System

Windows

### Hardware architecture

x86

### Which interface are you using?

Python bindings

### Contact Details

ardito.bryan@gmail.com

### Are you open to being tagged as a contributor?

- [x] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
@arditobryan, thanks for opening the issue! I suspect the issue is coming from the layout of the matrix, being a transposed view of column-major matrix, rather than a row major one. Can you double check that?

1. Check arr.flags['C_CONTIGUOUS']: Tells you if it’s laid out in a way that standard row-major functions can iterate without extra copying.
2. Check arr.base: Tells you if it’s a view of another array.
3. Inspect arr.strides: Gives deeper insight into how data is actually arranged in memory.

**Comment by arditobryan** [comment]
Thank you @ashvardanian it worked!
This was the issue:
```
>>> quantized_tfQ.flags['C_CONTIGUOUS']
False
```
To turn it True:
```
>>> quantized_tfQ = np.ascontiguousarray(quantized_tfQ)
>>> quantized_tfQ.flags['C_CONTIGUOUS']
True
```
Now the indexing works properly

**Comment by ashvardanian** [comment]
I'll merge patch that raises an exception when the input is not continuous. Thanks for help, @arditobryan!
