### ISSUE TITLE
Feature: Removing vectors

### ISSUE THREAD

**Issue by ashvardanian** [unum-cloud/usearch#62]
### Describe what you are looking for

[Removing efficiently isn’t trivial](https://github.com/nmslib/hnswlib/issues/4), but can be a minimal base solution to adapt USearch to caching tasks, and integrate into Semantic Kernel, LangChain, etc. 

### Can you contribute to the implementation?

- [X] I can contribute

### Is your feature request specific to a certain interface?

It applies to everything

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aehlke** [comment]
this blocks usage in langchain?

**Comment by ashvardanian** [comment]
Partly, but it should be ready within a few days.

**Comment by ashvardanian** [comment]
The `remove` interface is already integrated into recent releases for C++ and Python. It will soon get into the other bindings as well. @Arman-Ghazaryan can you please take over porting that functionality to other languages? As for LangChain, @aehlke, the integration is already on the way. @davvard is on it 🚀

**Comment by ashvardanian** [comment]
C99 interface now also offers `usearch_remove` from 20725403c196f6810133021d469a67faceb92193

**Comment by ashvardanian** [comment]
Now also present in Rust dc252fe2927d277d3cc7394a3a6b15c18decb2c6 and JavaScript be425325c829d6821329624bb1a582234579fe71

**Comment by jlarmstrongiv** [comment]
Is JavaScript support both Node and Browser WASM?

**Comment by ashvardanian** [comment]
@jlarmstrongiv, Node and server-side WASM have been tested. For browser, we are expecting news from our colleagues from @wasmerio: #191

**Comment by Arman-Ghazaryan** [comment]
Java interface now also offers usearch_remove and usearch_rename from [](https://github.com/unum-cloud/usearch/commit/387b78b28b17b8954024ffc81e97cbcfa10d1f30)
