### ISSUE TITLE
Feature: parsing more complex tensor's scalars types

### ISSUE THREAD

**Issue by kimihailv** [unum-cloud/usearch#70]
### Describe what you are looking for

Currently, usearch can parse only exact dtypes (f8, f32 and etc). But tensors can have more complex description of scalars' type. For instance, numpy `__array_interface__` property can return something like this:

`{'data': (140283485917200, False), 'strides': None, 'descr': [('', '<f4')], 'typestr': '<f4', 'shape': (1183514, 100), 'version': 3}`

So, it'd be useful If usearch supported dtypes like this.

### Can you contribute to the implementation?

- [ ] I can contribute

### Is your feature request specific to a certain interface?

It applies to everything

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Sure, it's an easy fix. Should be done by the next release. Thank you!
