### ISSUE TITLE
Bug: require(usearch) doesn’t work in node.js

### ISSUE THREAD

**Issue by alphapiper** [unum-cloud/usearch#80]
### Describe the bug

This was brought up and discussed in discord channel.

Node 18.0.0
Error: Cannot find module 'usearch' at Module.require (node:internal/modules/cjs/loader:1005:19) {code: 'MODULE_NOT_FOUND', requireStack: Array(16), stack: 'Error: Cannot find module 'usearch'Require s…re (node:internal/modules/cjs/loader:1005:19)', message: 'Cannot find module 'usearch'

even though my package.json has the dependency installed for "usearch": "^0.9.5”

Also, when directly using usearch.node as require(usearch.node), we get below error:
error: /src/binaries/usearch.node: invalid ELF header

### Steps to reproduce

in a node js file:
npm install usearch

then add below code
var usearch = require('usearch’);var index = new usearch.Index({ metric: 'cos', connectivity: 16, dimensions: 3 });index.add(42, new Float32Array([0.2, 0.6, 0.4]));var results = index.search(new Float32Array([0.2, 0.6, 0.4]), 10);console.log(results);

### Expected behavior

ability to use require(‘usearch’) 

### USearch version

v0.9.5

### Operating System

Ubuntu

### Hardware architecture

x86

### Which interface are you using?

Other bindings

### Contact Details

ap@alpha-piper.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ishkhan42** [comment]
`usearch.node` is not meant to be used in directly
