### ISSUE TITLE
Feature: Get labels and vectors from index

### ISSUE THREAD

**Issue by leoplusx** [unum-cloud/usearch#93]
### Describe what you are looking for

I'd like to be able to access all labels stored inside an index. I'd also like to be able to access vectors from the index by id.

hnswlib has these methods:
- index.get_items(ids)
- get_ids_list()

I find them useful, and am missing them in usearch.

### Can you contribute to the implementation?

- [ ] I can contribute

### Is your feature request specific to a certain interface?

Python bindings

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
@leoplusx I managed to implement those today and they are already available in the latest release. You can use `index.labels` property to get all labels, use `index[x]` to get one vector under the `x` label, and check if it's present with the simple `in` operator. More enhancements coming soon!

**Comment by leoplusx** [comment]
Actually, it doesn't seem to work. At least in Python:

Label values all seem to be 0.

Even though, when I run a search, it's clear that there actually are non-zero labels in the index.

Code example:

```

matches, distances, count  = iu.search(emb_np, k=10)
matches
> array([36517119, 38332614, 38332473, 38332625, 35783650, 38332484,
       36786081, 36927136, 38642553, 37563334])

iu[36517119]
> IndexError: Couldn't find key.

len(iu.labels)
> 3361000

len(set(iu.labels))
> 1

iu.labels[:10]
> array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
```

**Comment by ashvardanian** [comment]
Oh, wow. The new tests cover it, so it must have been solved, but not yet released. Will push the new release sooner.
