### ISSUE TITLE
Question/Feature: Does "view" allow adding new items directly to disk?

### ISSUE THREAD

**Issue by leoplusx** [unum-cloud/usearch#97]
### Describe what you are looking for

AFAIK, "view" allows us to memory map the index to disk. This way, we can load an index that doesn't fit into RAM.

I was just wondering if that will also work for adding items to an index.

If so, what is the process?

1. Instantiate the index
2. index.save()
3. index.view() from file
4. index.add()

If that does work, is it necessary to call index.save() again at any point, or will each index.add() operation directly write to disk?

If memory mapping does not work for adding items, then we will always need a machine with enough RAM to hold the entire index at least for the creation of that index, or for any adding operation. Is that correct?

Thanks.

### Can you contribute to the implementation?

- [ ] I can contribute

### Is your feature request specific to a certain interface?

Python bindings

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
For now, its not supported, but its two minor releases away. It won’t be done through `add` and will instead use the upcoming `merge` feature #84

**Comment by leoplusx** [comment]
Let me see if I understand who it would work:

Let's say I have a machine with 128 GB RAM and 300 GB of index data - so more data than would fit into RAM.

It sounds as though I could then assemble such an index like this:

1. Create sub-indices:
   - 100 GB -> index1 (create in RAM, then write to disk)
   - 100 GB -> index2 (create in RAM, then write to disk)
   - 100 GB -> index3 (create in RAM, then write to disk)

2. Use `merge` to merge those indices on disk into one large index on disk, without loading any of them into RAM.

3. Use `view` to search that large index, without loading it into RAM.

Is that how it would work?

**Comment by sctrueew** [comment]
@leoplusx, @ashvardanian Hi, I hope you're doing well.

I am working with approximately 10 million vectors, each with a dimensionality of 8,400. However, my available resources are somewhat limited:

RAM: 64 GB
Storage: 5 TB HDD
Given these constraints, what would be the best configuration for indexing and searching efficiently? Should I consider splitting the index, for example, creating 10 separate indexes with 1 million vectors each and then merging them later? Would this approach improve performance, or is there a better strategy for handling such high-dimensional data efficiently?

Additionally, do you have any recommendations for configurations, such as quantization techniques or PCA, to optimize for both memory usage and search speed?

I appreciate your insights. Thanks in advance!

**Comment by ashvardanian** [comment]
It’s a fairly small dataset @sctrueew. You can fit everything in RAM in one index 😉

**Comment by sctrueew** [comment]
@ashvardanian, my dataset is continuously growing, and it is expected to reach 100 million vectors within the next six months. However, I want to plan ahead and optimize my indexing strategy in advance. The data is being added incrementally over time, so I need a solution that can efficiently handle this growth without requiring a complete reindexing every time new data is added.

What would be the best approach for handling this dynamic expansion while ensuring efficient search performance and memory management? how can I minimize the impact on search speed as the dataset scales?

I would greatly appreciate any recommendations.
